---
- include_vars: grafana_server.yml

- name: Grafana ->  install
  include: grafana_server/install.yml

- name: Grafana -> configure
  include: grafana_server/config.yml

- name: Grafana -> provision
  include: grafana_server/provision.yml

- name: Grafana -> service 
  include: grafana_server/service.yml


