---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"

- name: reload systemd
  systemd:
    name: systemd
    daemon_reload: true

- name: reload service firewalld
  systemd:
    name: firewalld
    daemon_reload: true
    state: reloaded

