---
- name: restart apache service
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"

- name: reload systemd
  systemd:
    name: systemd
    daemon_reload: true

- name: reload firewalld service
  systemd:
    name: firewalld
    daemon_reload: true
    state: reloaded

- name: stop grafana service
  service:
    name: "{{ grafana_service_name }}"
    state: stopped

- name: start grafana service
  service:
    name: "{{ grafana_service_name }}"
    state: started

- name: restart grafana service
  service:
    name: "{{ grafana_service_name }}"
    state: restarted

- name: restart prometheus service
  service:
    name: "{{ prometheus_service_name }}"
    state: restarted

- name: restart node_exporter service
  service:
    name: "{{ node_exporter_service_name }}"
    state: restarted
  become: true

