---
- name: Create /etc/prometheus directory if it does not exist
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create configuration file
  template:
    src: prometheus_server/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - restart node_exporter service

- name:  Configure SNMP
  include:  prometheus_server/snmp.yml
  when:  (install_prometheus_snmp is defined) and install_prometheus_snmp == True

